version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "expense-api"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1f4bw2v7hj07"
s3_prefix = "expense-api"
region = "eu-west-1"
confirm_changeset = false
capabilities = "CAPABILITY_IAM"
